//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyJukebox.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tFileInfo
    {
        public int ID { get; set; }
        public int ID_Song { get; set; }
        public Nullable<int> FileSize { get; set; }
        public Nullable<System.DateTime> FileDate { get; set; }
        public Nullable<System.TimeSpan> Duration { get; set; }
        public Nullable<System.DateTime> ImportDate { get; set; }
        public string Link { get; set; }
    }
}
